<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MY_Model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    function _get_config($key = "") {
        $config = $this->db->get_where('config', array('key' => $key));
        if ($this->db->_error_message() == "") {
            if ($config->num_rows() > 0) {
                $config = $config->row();
                $config = unserialize(base64_decode($config->value));
                return $config;
            } else {
                return false;
            }
        } else {
            //debug( $this->db->_error_message() ); //uncomment to see the error
            return false;
        }
    }

    function _get_meta() {
        $app_dir = $this->_get_config('app_directories');
        $meta_file = $app_dir['system_settings_dir'] . 'meta.php';
        $this->load->helper('file');
        if (file_exists($meta_file)) {
            require_once( $meta_file );
        } else {
            $meta = $this->_get_config('meta');
            //write data to file
            $to_write = '<?php $meta = ' . var_export($meta, true) . '; ?>';
            write_file($meta_file, $to_write);
        }
        $year = date('Y');
        foreach ($meta as $key => $config) {
            eval("\$config = \"$config\";");
            $meta[$key] = $config;
            $$key = $meta[$key];
        }
        return $meta;
    }

    function _update_config($key = "", $value = "") {
				//check existence of config
				$config = $this->db->get_where('config', array('key' => $key));
				
				if( $config->num_rows() == 0 ){
					$this->db->insert('config', array('key' => $key, 'value' => $value));
				}
				else{
					$this->db->where('key', $key);
					$this->db->update('config', array('value' => $value));
				}
    }

    function _get_user_config($key = "", $user_id = 0) {
        $config = $this->db->get_where('user_config', array('key' => $key, 'user_id' => $user_id));
        if ($this->db->_error_message() == "") {
            if ($config->num_rows() > 0) {
                $config = $config->row();
                $config = unserialize(base64_decode($config->value));
                return $config;
            } else {
                return false;
            }
        } else {
            //debug( $this->db->_error_message() ); //uncomment to see the error
            return false;
        }
    }

    function _update_user_config($key = "", $value = "", $user_id = 0) {
        if ($this->db->get_where('user_config', array('key' => $key, 'user_id' => $user_id))->num_rows() > 0) {
            $this->db->where(array('key' => $key, 'user_id' => $user_id));
            $this->db->update('user_config', array('value' => $value));             
        } else {
            $this->db->insert('user_config', array('key' => $key, 'value' => $value, 'user_id' => $user_id));
        }
    }

    /**
     * just a quick see at the last query generated by active record
     * @return [type] [description]
     */
    function last_query(){
       dbug($this->db->last_query());
    }

    /* End of file MY_Model.php */
    /* Location: ./application/core/MY_Model.php */
}